base_url: "https://opensource-demo.orangehrmlive.com/web/index.php/auth/login"
browser: "chromium"
headless: False
#screenshot_path: "C:\\Users\\lenovo\\PycharmProjects\\Playwright_Framework_July\\Screenshots\\"
screenshot_path: "C:/Users/lenovo/PycharmProjects/Playwright_Framework_July/Screenshots/"
log_path: "Logs/test.log"
username: "Admin"
encrypted_password: "YWRtaW4xMjM="   # base64 encoded 'admin123'

