base_url: "https://opensource-demo.orangehrmlive.com/web/index.php/auth/login"
browser: "chromium"  # firefox, webkit
headless: False
ss_path: "./Screenshots/"
username: "Admin"
encrypted_password: "YWRtaW4xMjM="   # base64 encoded 'admin123'
